### PR TITLE
Refactor psql migrations

### PR DESCRIPTION
**Pull request by rohanthewiz**
Migrating a fresh postgres database errs out as psql was missing user credentials. Also a given user cannot run a migration to create the user (chicken and the egg situation). I solved the problem by creating the user in psql before the fragmenta migration and passing those creds into fragmenta new at a prompt.

### CODE REVIEW

**Comment by kennygrant** [comment]
Thanks for the pull request. I did have some plans to remedy this but will also have a look at what you've done here and see if I can merge some of it. I'm very busy just now but will try to look at this soon.

**Comment by rohanthewiz** [comment]
Awesome! This is a some great work that you've done here.

**Comment by kennygrant** [comment]
See #1 - the best solution is probably to get rid of refs to the psql binary (the db may be remote as well), and do migrations by executing sql line by line using the driver instead. So please leave this for now and I'll try to sort it out that way. The onboarding definitely needs some work, as at present it is tested with psql and requires some manual setup.

**Comment by rohanthewiz** [comment]
Yes using the driver is better, and no sweat, I only wanted to show one way it could be done. Regardless, the postgres user used by the driver should be created first, yes? And it's probably not best to use the 'postgres' superuser.

**Comment by kennygrant** [comment]
I may still use some of this, and yes the bootstrapping an initial user and db is the biggest problem point for new users. I've been surprised by how much of a hurdle that is, and need to improve it. If you have thoughts on how that should work it'd be really interesting to hear them.

**Comment by rohanthewiz** [comment]
I think the Rails approach is reasonable. I can create a new project with a rails generator and specify the use of Postgres, but then the user has to update the configuration file before the server is launched.  Hmm, perhaps creds can be a option to fragmenta new.  If no creds supplied then at the end remind the user to "Update fragmenta.json with your database user and password".
Setting up the database user should be out of the scope of Fragmenta. Helpful notes and links can be provided in a Readme, but should really be a separate concern as it is a detailed topic. (Most times in PG I have to edit the hba.conf file to tell it to use  "local" instead of "password" i.e. a pain.)
I am sure you want to get to the point of being database agnostic. SQLite could be a future option too.
Anyway again, great job on the complete pakage here. Take a look at this: calvaryeastmetro.com.

**Comment by kennygrant** [comment]
There are two problems with current behaviour here as you point out:  

* We need to use the db driver to perform migrations - see issue #1
* Initial bootstrap migrations require privileges and is a major pain point - see issue #28

The bootstrap issue is a tricky one, because of different working styles, and different requirements between just trying the app out for development and in production. I never bootstrap on a production server, hence the current setup, but think it needs further discussion and a decision made. Have opened issue # for that. 

I'm going to close this pull request now in favour of discussion on the issues as I have an issue open for it and it now conflicts with later changes. Thanks for the ideas above, this is definitely the main stumbling block for people at the minute and does need a better solution.

**Pull request closed without merging**
